# yaml-language-server: $schema=https://json.schemastore.org/spring-boot-application.json

server:
  port: 8081

spring:
  profiles:
    active: dev

langchain4j:
  open-ai:
    chat-model:
      model-name: deepseek-v4-pro
      api-key: ${langchain4j.alibailian.api-key}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
  community:
    dashscope:
      chat-model:
        api-key: ${langchain4j.alibailian.api-key}
        model-name: qwen3.6-max-preview

logging:
  level:
    root: info
    com.atguigu: info
    dev.langchain4j: warn
